In [63]:
import open3d as o3d
from o3d_tools.visualize import PointCloudProject

import numpy as np
import pandas as pd

In [31]:
project1 = PointCloudProject(project='Project1')
project2 = PointCloudProject(project='Project2')
project3 = PointCloudProject(project='Project3')
project4 = PointCloudProject(project='Project4')

In [45]:
objs1 = project1.objects_df

print(f"Types of objects in Project 1: {list(objs1.keys())}")
pipes1 = objs1["Pipe"]
scbs1 = objs1["Structural_ColumnBeam"]
sibs1 = objs1["Structural_IBeam"]
hvducts = objs1["HVAC_Duct"]

objs2 = project2.objects_df

print(f"Types of objects in Project 2: {list(objs2.keys())}")
pipes2 = objs2["Pipe"]
scbs2 = objs2["Structural_ColumnBeam"]
sibs2 = objs2["Structural_IBeam"]

objs3 = project3.objects_df

print(f"Types of objects in Project 3: {list(objs3.keys())}")
scbs3 = objs3["Structural_ColumnBeam"]

objs4 = project4.objects_df

print(f"Types of objects in Project 4: {list(objs4.keys())}")
sibs4 = objs4["Structural_IBeam"]

Types of objects in Project 1: ['Structural_ColumnBeam', 'HVAC_Duct', 'Pipe', 'Structural_IBeam']
Types of objects in Project 2: ['Structural_ColumnBeam', 'Pipe', 'Structural_IBeam']
Types of objects in Project 3: ['Structural_ColumnBeam']
Types of objects in Project 4: ['Structural_IBeam']


In [46]:
masks1 = project1.masks
masks2 = project2.masks
masks3 = project3.masks
masks4 = project4.masks

In [84]:
boxes1 = pd.concat([scbs1, hvducts, pipes1, sibs1])
#boxes1 = pd.concat([pipes1, scbs1, sibs1, hvducts])
boxes2 = pd.concat([scbs2, pipes2, sibs2])
boxes3 = scbs3
boxes4 = sibs4

In [85]:
points1

array([[-212.7340879 ,  345.58831876,   99.63829874],
       [-213.17639459,  345.79170158,   99.48409927],
       [-213.05974063,  346.73293539,   98.18160583],
       ...,
       [-241.88225843,  345.7760487 ,   85.49421455],
       [-242.53620517,  347.90347885,   86.52111743],
       [-243.06067268,  346.45728136,   85.69106494]])

In [86]:
boxes1

ID                  Label   BB.Min.X   \
0   d442ca7c-770d-4bc2-a565-81b971e1b3b3  Structural_ColumnBeam -221.953285   
1   de9a038a-e106-48fa-ac76-3f83dfa1503a  Structural_ColumnBeam -221.953285   
2   b351dae6-0cf2-45f2-bbfd-ab9e607bce0d              HVAC_Duct -206.833503   
3   62e75328-ddda-48d4-87c4-210afb055eb5              HVAC_Duct -204.791837   
4   64ca25ff-ebc8-4e83-9585-756d6b711a3c              HVAC_Duct -204.791837   
..                                   ...                    ...         ...   
77  35c48b35-4cca-45be-9451-a757629a9c3f       Structural_IBeam -243.984615   
78  82329065-2e17-4808-85d7-ceb7bbf82209       Structural_IBeam -221.975367   
79  4163a59b-36f3-44a7-a77f-20f3b96cc3ed       Structural_IBeam -221.453406   
80  5375cc03-28fe-432c-908a-5137b84502de       Structural_IBeam -221.453408   
81  62ed7cd0-481a-47a7-9fef-120c01a3a75c       Structural_IBeam -243.984615   

     BB.Min.Y    BB.Min.Z    BB.Max.X    BB.Max.Y     BB.Max.Z  
0   334.091068   83.833336 -219.536613  336.507724   98.874596  
1   315.091068   83.833336 -219.536613  317.507724   98.874611  
2   337.267214   95.083333 -203.333503  341.100548   98.250000  
3   332.154501   94.708333 -200.041837  338.154501   98.625000  
4   327.477417   94.708333 -200.041837  334.144084   98.625000  
..         ...         ...         ...         ...         ...  
77  324.570229   96.567821 -220.017024  327.028562  100.343174  
78  317.299394   97.024534 -219.514534  335.257733  100.349596  
79  334.068980   97.031106 -185.310403  336.529813  101.082445  
80  339.902313   97.031102 -185.310402  342.363147  101.082445  
81  345.736897   96.567629 -220.036608  348.195230  100.342779  

[82 rows x 8 columns]

In [53]:
points1 = np.asarray(project1.pcd.points)
colors1 = np.asarray(project1.pcd.colors)

points2 = np.asarray(project2.pcd.points)
colors2 = np.asarray(project2.pcd.colors)

points3 = np.asarray(project3.pcd.points)
colors3 = np.asarray(project3.pcd.colors)

points4 = np.asarray(project4.pcd.points)
colors4 = np.asarray(project4.pcd.colors)

In [58]:
points1

array([[-212.7340879 ,  345.58831876,   99.63829874],
       [-213.17639459,  345.79170158,   99.48409927],
       [-213.05974063,  346.73293539,   98.18160583],
       ...,
       [-241.88225843,  345.7760487 ,   85.49421455],
       [-242.53620517,  347.90347885,   86.52111743],
       [-243.06067268,  346.45728136,   85.69106494]])

In [73]:
colors1

array([[0.09765625, 0.09765625, 0.09765625],
       [0.12109375, 0.12109375, 0.12109375],
       [0.30859375, 0.30859375, 0.30859375],
       ...,
       [0.21484375, 0.21484375, 0.21484375],
       [0.33203125, 0.33203125, 0.33203125],
       [0.78125   , 0.78125   , 0.78125   ]])

In [57]:
pipes1

ID  Label   BB.Min.X    BB.Min.Y   \
14  2415192b-829b-433a-a99e-37fe0f0ca058   Pipe -236.677753  308.494775   
15  7a1a3baa-5bea-48ab-9220-40eb561916f2   Pipe -221.095112  311.719731   
16  274f563c-c2ec-4611-a848-b8cba66bc303   Pipe -210.329439  326.024954   
17  1246b8e8-dcb6-4066-8c8c-92b014a1d3ce   Pipe -214.325569  304.717662   
18  4b3af85f-9310-41b0-9248-87a5b68f1bdf   Pipe -189.022148  326.024954   
19  5b49ef94-9baa-40b5-971c-ea6c0d983d99   Pipe -213.132558  326.024954   
20  4d607eda-df93-406e-8b6c-dad12c83b232   Pipe -241.898855  303.497555   
21  6144e713-81de-428e-9583-6557a97da649   Pipe -241.898855  306.164222   
22  ddae7b02-9cbe-4fcd-8948-43c2d5d60b0e   Pipe -235.718626  309.838133   
23  63823dc5-5fc1-4aa4-bd71-4baf54737920   Pipe -241.495298  309.936131   
24  604aa493-11d2-4dd3-8ddc-773acfd11167   Pipe -223.966322  291.171163   
25  c086b354-ee21-4219-914e-42e1f9a7e584   Pipe -223.966322  291.171163   
26  c9d85e88-6af5-4927-a7bd-0ea268fc0bfc   Pipe -234.689980  291.192080   
27  0ee2aff0-a510-4979-a877-ff8839d43b53   Pipe -194.520310  334.744776   
28  c09cffb3-c6df-47f3-927d-533289b2349e   Pipe -242.969033  318.405718   
29  0764ba93-5aeb-488a-9f49-3e39905f29af   Pipe -220.421875  315.510130   
30  39c37656-df1e-45e4-9433-c3859a944287   Pipe -216.926528  307.295944   
31  61c306ff-dd2b-4801-9485-ad70f2e287c3   Pipe -217.697362  306.669541   
32  ea3bb563-19f5-4260-9315-e872d9c1f432   Pipe -232.749291  310.635092   
33  95a0f1ac-79dc-44a6-8fa9-ddd5489d1410   Pipe -222.835262  299.729154   
34  b64f328c-b7ca-4af9-857c-5aebb483ac24   Pipe -234.648227  325.116560   
35  9db87722-0f87-466d-acdc-7ed042690d66   Pipe -239.652855  339.715675   
36  fa7d7a21-bf66-41b6-9877-0b26f756cdfc   Pipe -210.339856  324.808962   
37  b6bf78ab-f65b-4b51-8cc9-93733e85d338   Pipe -189.022148  324.808962   
38  2891ff44-45e2-4a2e-9fe5-f85bb0182558   Pipe -213.161444  321.158102   
39  ec7cc752-4e3f-4d21-b1bc-1f2f4f5b8240   Pipe -215.260155  326.805994   
40  c9e5f5f4-b729-4192-b0f5-63d80a2c2e77   Pipe -196.668345  329.074244   
41  3f961d67-a7a5-40eb-8b7e-60ce69d2fb43   Pipe -194.843909  326.868494   
42  718e5719-b651-449a-a40a-e2a262abfa29   Pipe -196.850637  324.026334   
43  fe20e390-249e-4dfe-a624-b929005c150d   Pipe -194.392304  321.526333   
44  b8b38c44-2f62-48d5-ad8a-48d667f577e8   Pipe -212.761347  324.305994   
45  33fb3883-bc5c-4dce-921a-149633c6af1f   Pipe -196.668345  334.584661   
46  86f8c6b5-24e8-4d73-9f48-723591ee0f55   Pipe -240.850772  328.796641   
47  5aaf0277-3886-474a-84c7-445a9f04a16a   Pipe -188.052498  328.227448   
48  b469889f-3aec-4a2e-a256-cbf7a1a3481e   Pipe -243.750416  328.232238   
49  7d40f84c-542d-423a-be0c-d0b013c58bb6   Pipe -243.750416  328.232238   
50  a064e314-a65f-4ccf-a1d1-836670df3094   Pipe -235.856560  325.116560   
51  f3ecda55-5c6c-4664-a83a-c149a50d71fc   Pipe -188.052498  328.227448   
52  0ae20593-998e-43be-94cb-e902f1185f8f   Pipe -235.856560  325.116560   
53  b2c38994-2e1a-4fa8-bba5-17a5d814b848   Pipe -222.851265  325.994776   
54  7346334f-2ad5-45d1-bbd7-fd19c4839ce7   Pipe -235.856560  336.533227   
55  c1777ff2-fd50-4b40-880c-d42c2b542214   Pipe -239.652855  328.796641   
56  dd292651-f9b1-4913-bf0a-b092cb2da485   Pipe -240.850772  339.715675   
57  1ebc8a18-ebb1-4a2a-88e0-1ae11f4cf583   Pipe -234.648227  336.533227   
58  82fa440a-f35d-4a1d-9b6c-7eabaa26f143   Pipe -236.686914  317.244771   
59  15bb308c-2ff8-4259-b7fd-62a0e8d22a89   Pipe -222.853644  334.744776   
60  ea588168-3f23-48ff-a9ac-f30cd599791d   Pipe -208.686977  334.744776   

     BB.Min.Z    BB.Max.X    BB.Max.Y    BB.Max.Z  
14   96.311586 -234.560618  319.015638  98.426503  
15   86.651815 -218.386769  314.428064  93.418258  
16   96.205853 -187.329439  328.910371  99.091269  
17   96.205853 -211.440153  327.717662  99.091269  
18   88.761699 -186.136731  328.910371  97.898561  
19   96.205853 -208.329439  328.910371  99.091269  
20   91.350000 -239.190522  306.205889  94.104171  
21   91.357808 -239.1